server:
  port: 8888

spring:
  rabbitmq:
    host: 180.76.231.102
    port: 5672
    username: root
    password: root
    publisher-confirm-type: correlated # NONE 值是禁用发布确认模式，是默认值CORRELATED 值是发布消息成功到交换器后会触发回调方法  SIMPLE 值经测试有两种效果，其一效果和 CORRELATED 值一样会触发回调方法，其二在发布消息成功后使用 rabbitTemplate 调用 waitForConfirms 或 waitForConfirmsOrDie 方法等待 broker 节点返回发送结果，根据返回结果来判定下一步的逻辑，要注意的点是 waitForConfirmsOrDie 方法如果返回 false 则会关闭 channel，则接下来无法发送消息到 broker
    publisher-returns: true
    template:
      mandatory: true #回退消息